name: Deploy CoreLib to GitHub Packages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Get current version from pom.xml
        id: get_version
        run: |
          VERSION=$(grep -m 1 '<version>' pom.xml | sed -E 's/.*<version>([^<]+)<\/version>.*/\1/')
          echo "Detected version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if version already exists on GitHub Packages
        id: check_version
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.mvn_deploy }}" \
            "https://maven.pkg.github.com/Lagtopia/core-lib/me/csdad/lagtopia/corelib/$VERSION/corelib-$VERSION.pom")

          if [[ "$RESPONSE" == "200" ]]; then
            echo "Version $VERSION already exists. Skipping deployment."
            echo "SKIP_DEPLOY=true" >> $GITHUB_ENV
          else
            echo "Version $VERSION does not exist. Proceeding to deploy."
          fi

      - name: Deploy to GitHub Packages
        if: env.SKIP_DEPLOY != 'true'
        run: mvn clean deploy --settings .github/settings.xml -X
        env:
          GITHUB_ACTOR: Lagtopia
          GITHUB_TOKEN: ${{ secrets.mvn_deploy }}
